#!/bin/sh

lxpolkit &
autorandr -c
sxhkd &
picom -b --config $XDG_CONFIG_HOME/picom/picom.conf
redshift &
udiskie -qF &
dunst &
#nm-applet &
xss-lock -- lock.sh &
xsetroot -cursor_name left_ptr
unclutter -idle 1 &
perWindowLayoutD
syncthing --no-browser &
