#!/bin/sh

lxpolkit &
autorandr -c
sxhkd &
picom -b --config $XDG_CONFIG_HOME/picom/picom.conf
redshift-gtk -l $(cat .config/gde.sum) &
udiskie -qF &
dunst &
xss-lock -- lock.sh &
xsetroot -cursor_name left_ptr
unclutter -idle 1 &
perWindowLayoutD
syncthing serve &
xfce4-power-manager &
