#! /bin/sh

# setup monitors
bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 10
monitors.sh

# general settings
bspc config split_ratio				0.50
bspc config automatic_scheme		spiral
bspc config initial_polarity		second_child
bspc config window_gap				4
bspc config border_width			2

# colors
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

# padding (4 + polybar_heigth + polybar_offset_y)
bspc config top_padding		 		26

# mouse actions
bspc config pointer_modifier 		mod4
bspc config pointer_action1	 		move
bspc config pointer_action2	 		none
bspc config pointer_action3	 		resize_corner

# rules
for i in `seq 1 $(bspc rule -l | wc -l)`; do bspc rule -r tail; done
bspc rule -a URxvt:scratchpad state=floating sticky=true locked=true
bspc rule -a URxvt:ranger state=floating
bspc rule -a URxvt:pcmnfm state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Oblogout state=fullscreen sticky=true
bspc rule -a Pcmanfm state=floating
bspc rule -a URxvt:spt desktop='8'
bspc rule -a Spotify desktop='8'
bspc rule -a Signal desktop='8'
bspc rule -a firefox -o desktop='2'
