#! /bin/sh

# setup monitors
bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 10
monitors.sh

# general settings
bspc config split_ratio				0.50
bspc config automatic_scheme		longest_side
bspc config initial_polarity		second_child
bspc config window_gap				3
bspc config border_width			2

# monocle settings
bspc config single_monocle			true
bspc config borderless_monocle		false
bspc config gapless_monocle			true
bspc config bottom_monocle_padding	3

# colors
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

# padding (4 + polybar_heigth + polybar_offset_y)
bspc config bottom_padding		 		22

# mouse actions
bspc config pointer_modifier 		mod4
bspc config pointer_action1	 		move
bspc config pointer_action2	 		none
bspc config pointer_action3	 		resize_corner

# rules
for i in `seq 1 $(bspc rule -l | wc -l)`; do bspc rule -r tail; done
bspc rule -a URxvt:scratchpad state=floating sticky=true locked=true
bspc rule -a URxvt:rofi state=floating
bspc rule -a Thunar state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Xfce4-taskmanager state=floating
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Spotify desktop='8'
bspc rule -a Signal desktop='8'
bspc rule -a firefox -o desktop='2'
