# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references the colours from your terminal theme: Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White.
theme:
  active: Blue # current playing song in list
  banner: Cyan # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: Red # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: Green # hovered pane border
  inactive: Blue # borders of inactive panes
  playbar_background: DarkGray # background of progress bar
  playbar_progress: Blue # filled-in part of the progress bar
  playbar_text: Magenta # artist name in player pane
  selected: Cyan # a) selected pane border, b) hovered item in list, & c) track title in player
  text: White # text in panes

